#!/usr/bin/env python3
"""Validate and package the ESP32-S3 NAT Router flash artifacts.

This project deliberately uses an OTA partition layout without a factory app:
  bootloader   0x00000000
  partition    0x00008000
  otadata      0x0000F000 (8 KiB, generated by ESP-IDF)
  ota_0 app    0x00020000 (1536 KiB)
  ota_1 app    0x001A0000 (1536 KiB)

The ESP-IDF build system creates build/ota_data_initial.bin when the project
contains a data/ota partition. We require that generated artifact to exist;
we never fabricate it here because doing so could mask a broken OTA layout.
"""
from pathlib import Path
import re
import sys

BUILD = Path("build")
ARTIFACTS = Path("artifacts")
PROJECT = Path(".")

EXPECTED = {
    0x00000000: BUILD / "bootloader" / "bootloader.bin",
    0x00008000: BUILD / "partition_table" / "partition-table.bin",
    0x0000F000: BUILD / "ota_data_initial.bin",
    0x00020000: BUILD / "esp32s3_nat_router.bin",
}

MAX_BOOTLOADER = 0x8000
PARTITION_TABLE_SIZE = 0x1000
OTA_SLOT_SIZE = 1536 * 1024
OTADATA_SIZE = 0x2000


def fail(message: str) -> "NoReturn":
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def require_file(path: Path) -> None:
    if not path.is_file():
        fail(f"Required build artifact is missing: {path}")
    if path.stat().st_size == 0:
        fail(f"Build artifact is empty: {path}")


def parse_flash_args(path: Path) -> dict[int, str]:
    require_file(path)
    text = path.read_text(encoding="utf-8", errors="replace")
    found: dict[int, str] = {}
    for line in text.splitlines():
        m = re.match(r"^\s*(0x[0-9a-fA-F]+)\s+(.+?)\s*$", line)
        if not m:
            continue
        found[int(m.group(1), 16)] = m.group(2).strip()
    return found


def main() -> None:
    ARTIFACTS.mkdir(parents=True, exist_ok=True)

    for path in EXPECTED.values():
        require_file(path)

    otadata_size = EXPECTED[0x0000F000].stat().st_size
    if otadata_size != OTADATA_SIZE:
        fail(f"ota_data_initial.bin must be {OTADATA_SIZE} bytes, got {otadata_size}")

    boot_size = EXPECTED[0x00000000].stat().st_size
    if boot_size > MAX_BOOTLOADER:
        fail(f"bootloader.bin is {boot_size} bytes and overlaps the partition table region")

    table_size = EXPECTED[0x00008000].stat().st_size
    if table_size > PARTITION_TABLE_SIZE:
        fail(f"partition-table.bin is {table_size} bytes and exceeds its 0x1000-byte region")

    app_size = EXPECTED[0x00020000].stat().st_size
    if app_size > OTA_SLOT_SIZE:
        fail(f"Application is {app_size} bytes but ota_0 is only {OTA_SLOT_SIZE} bytes")

    flash_args = parse_flash_args(BUILD / "flash_args")
    expected_args = {
        0x00000000: "bootloader/bootloader.bin",
        0x00008000: "partition_table/partition-table.bin",
        0x0000F000: "ota_data_initial.bin",
        0x00020000: "esp32s3_nat_router.bin",
    }
    for offset, name in expected_args.items():
        actual = flash_args.get(offset)
        if actual is None:
            fail(f"build/flash_args has no entry at 0x{offset:08X}")
        if Path(actual).name != Path(name).name:
            fail(f"build/flash_args maps 0x{offset:08X} to '{actual}', expected '{name}'")

    # Copy the individual files into the published artifact directory.
    copies = {
        "esp32s3_bootloader.bin": EXPECTED[0x00000000],
        "esp32s3_partition-table.bin": EXPECTED[0x00008000],
        "ota_data_initial.bin": EXPECTED[0x0000F000],
        "esp32s3_app.bin": EXPECTED[0x00020000],
        "flash_args.txt": BUILD / "flash_args",
    }
    for dst_name, src in copies.items():
        require_file(src)
        (ARTIFACTS / dst_name).write_bytes(src.read_bytes())

    # Produce an explicit one-offset factory image. It mirrors the four
    # flash entries above and is safe to write starting at 0x00000000.
    pieces = [(offset, path.read_bytes()) for offset, path in EXPECTED.items()]
    end = max(offset + len(data) for offset, data in pieces)
    merged = bytearray(b"\xFF" * end)
    for offset, data in pieces:
        merged[offset:offset + len(data)] = data
    (ARTIFACTS / "esp32s3_nat_router_factory.bin").write_bytes(merged)

    instructions = PROJECT / "FLASH_INSTRUCTIONS.txt"
    require_file(instructions)
    (ARTIFACTS / instructions.name).write_bytes(instructions.read_bytes())

    print("Flash artifact validation passed.")
    for offset, path in EXPECTED.items():
        print(f"  0x{offset:08X}  {path}  ({path.stat().st_size} bytes)")
    print(f"  factory image: {(ARTIFACTS / 'esp32s3_nat_router_factory.bin').stat().st_size} bytes")


if __name__ == "__main__":
    main()
